name: Events Demo 1
on:   # EVENTS below will trigger the workflow
  pull_request: # Triggered by PR
    types: [opened, edited]
    # # You can also add the branches filter here, not only in the "push:"" event
    # branches:
    #   - main
    #   - 'dev-*'
    #   - 'feat/**' 
    
  workflow_dispatch:   # Triggered manually
  push: # Triggered by a push
    branches:
      - main
      - 'dev-*'
      - 'feat/**' # All branches staring with "feat/", including additinal forward slashes after the first one.\

      # path: # If file(s) is changed in a specific path/folder
    paths-ignore: # If there is a change in file(s) exept a specific path/folder
      - ".github/workflows/*"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."


# # On push and manually
# name: Events Demo 1
# on: [push, workflow_dispatch]
# jobs:
#   deploy:
#     runs-on: ubuntu-latest


# # Second way to define a list
# name: Events Demo 1
# on:
#   pull_request:
#     types:
#       - opened
#       - edited
# jobs: